### ISSUE TITLE
Have you reviewed the pre-existing FAPI conformance suites?

### ISSUE THREAD

**Issue by jh-a** [ConsumerDataStandardsAustralia/conformance#63]
Please check https://openbanking.atlassian.net/wiki/spaces/DZ/pages/23856067/OB+OIDC+Conformance+Suite and https://fintechlabs-fapi-conformance-suite.fintechlabs.io/login.html which already tests FAPI conformance / compliance.

**Comment by benkolera** [comment]
Hi @jh-a. I realised that I answered this on the open-banking-global slack but not in here. So copying that message verbatim so that people here can see it! :slightly_smiling_face: 

> We are definitely aware of the FAPI suite, but we've got a testing technique that is really good at testing stateful APIs by it generating random sequences of interleaving commands and shaking out concurrency race conditions and out of order message bugs that you would never even think to unit test. There is a really good paper outlining the technique and the real bugs that it found in software in actual cars here: https://pdfs.semanticscholar.org/76c7/ddcaadee1fc0b475df59c08bf0700313586d.pdf  It's a bit of a "this may be awesome or it may not be any better than the unit tests due to technical and logistical constraints of the Australian work". We haven't been able to be very open about it yet because understandably there is limited bandwidth to the public and we're a team with a weird idea that no one knows is a good idea or not yet so we are at the back of the queue for bandwidth. Though TBH most of our work so far has been playing around implementing the non-auth standards in our mock bank and giving feedback to the standards. We should get our chance to talk to people soon and see if the idea will work for the involved stakeholders; but we'd expect our state machine testing to sit side by side with the OIDF unit test suite in a perfect world (and even contribute any common issues found from the randomised testing back to the unit tests, if there are any).
